// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartTrafficMonitor.Models;

#nullable disable

namespace SmartTrafficMonitor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260303063348_AddSensorLocations")]
    partial class AddSensorLocations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartTrafficMonitor.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Action");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("Details");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("Ip");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("Success");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TimestampUtc");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text")
                        .HasColumnName("UserEmail");

                    b.HasKey("Id");

                    b.ToTable("auditlog", "public");
                });

            modelBuilder.Entity("SmartTrafficMonitor.Models.SensorLocation", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sensor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SensorId"));

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("SensorSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sensor_slug");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone");

                    b.HasKey("SensorId");

                    b.HasIndex("SensorSlug")
                        .IsUnique();

                    b.ToTable("sensor_locations", "public");
                });

            modelBuilder.Entity("SmartTrafficMonitor.Models.TrafficData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direction")
                        .HasColumnType("text")
                        .HasColumnName("Direction");

                    b.Property<int>("FootTrafficCount")
                        .HasColumnType("integer")
                        .HasColumnName("FootTrafficCount");

                    b.Property<string>("MovementType")
                        .HasColumnType("text")
                        .HasColumnName("MovementType");

                    b.Property<bool>("PublicTransportRef")
                        .HasColumnType("boolean")
                        .HasColumnName("PublicTransportRef");

                    b.Property<string>("Season")
                        .HasColumnType("text")
                        .HasColumnName("Season");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("SensorId");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TimeStamp");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("integer")
                        .HasColumnName("VehicleCount");

                    b.Property<bool>("VuScheduleRef")
                        .HasColumnType("boolean")
                        .HasColumnName("VUScheduleRef");

                    b.HasKey("Id");

                    b.HasIndex("MovementType");

                    b.HasIndex("Season");

                    b.HasIndex("SensorId");

                    b.HasIndex("Timestamp");

                    b.ToTable("traffictable", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
