// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartTrafficMonitor.Models;

#nullable disable

namespace SmartTrafficMonitor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartTrafficMonitor.Models.TrafficData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direction")
                        .HasColumnType("text");

                    b.Property<int>("FootTrafficCount")
                        .HasColumnType("integer");

                    b.Property<string>("HeatmapPeriod")
                        .HasColumnType("text");

                    b.Property<string>("MovementType")
                        .HasColumnType("text");

                    b.Property<bool>("PublicTransportRef")
                        .HasColumnType("boolean");

                    b.Property<string>("Season")
                        .HasColumnType("text");

                    b.Property<string>("SensorId")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("VUScheduleRef")
                        .HasColumnType("boolean");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TrafficDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
